server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Change this to your GitHub repository URL once created and pushed
          uri: https://github.com/smadhuranga/stock-config-server.git
#          uri: file://${user.home}/Desktop/CL/stock-main/stock-config-repo
          search-paths: stock-service, supplier-service, file-service, api-gateway, eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
